### ISSUE TITLE
Search Index Page - Yard Show redirect

### ISSUE THREAD

**Issue by jbranham1** [Yardsourcing/yardsourcing-frontend#43]
As a user, when I visit search_index, and I see yard tabs in the search results, I can click on a tab and it takes my to that yards show page

**Comment by dev-named-jordan** [comment]
It seems that maybe 2 cards were made for this task? It appears this functionality is already in the app.

**Comment by jbranham1** [comment]
@jordanfbeck0528 Agreed! Closed out this issue
